src/ros/scan2bag.cc: move scan.h after bag.h
Since scan.h now includes newmatap.h, there is a symbol clash with
rosbag.constants.h:

In file included from /usr/include/newmat/include.h:10,
                 from /usr/include/newmat/newmat.h:8,
                 from /usr/include/newmat/newmatap.h:8,
                 from ../include/slam6d/scan.h:27,
                 from ../src/ros/scan2bag.cc:6:
/usr/include/rosbag/constants.h:44:26: error: expected unqualified-id before string constant
 static const std::string VERSION = "2.0";
                          ^~~~~~~

Thus we include scan.h *after* rosbag/bag.h

git-svn-id: svn+ssh://svn.code.sf.net/p/slam6d/code/trunk@2227 51f1e6e7-7289-49ad-8748-f09e43fc6daa